---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: heading
  label: lafm
- type: directory
  path: content/lafmautores
  label: lafm-autores
  create: documents
  match: "**/*"
  templates:
  - lafm-autor-collection
- type: directory
  path: content/lafmstories
  label: lafm-stories
  create: documents
  match: "**/*"
  templates:
  - lafm-storie-collection
- type: directory
  path: content/lafmtipos
  label: lafm-tipos
  create: documents
  match: "**/*"
  templates:
  - laft-tipo-collection
- type: directory
  path: content/lafmpubs
  label: lafm-pubs
  create: documents
  match: "**/*"
  templates:
  - lafm-pub-collection
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
