---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: directory
  path: content/lafm/pubs
  label: lafm-pubs
  create: all
  match: "**/*"
  templates:
  - lafm-pub-collection
- type: directory
  path: content/lafm/tipos
  label: lafm-tipos
  create: all
  match: "**/*"
  templates:
  - lafm-tipo-collection
- type: directory
  path: content/lafm/autores
  label: lafm-autores
  create: all
  match: "**/*"
  templates:
  - lafm-autor
- type: directory
  path: content/lafm/stories
  label: lafm-stories
  create: all
  match: "**/*"
  templates:
  - lastorie
upload_dir: archivos
public_path: "/archivos"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
